
version: '3'
services:

  server:
    build: .
    container_name: application

    ports:
    - "8000:8000"

    env_file:
      - .env
    depends_on:
      - database


  database:
    ports:
      - "4444:5432"
    image: postgres
    container_name: app-database
    env_file:
      - .env